<?php
/**
 * MappingNotFoundException.php
 *
 * PHP Version 5
 *
 * @category Bragento_MagentoComposerInstaller
 * @package  Bragento_MagentoComposerInstaller
 * @author   David Verholen <david@verholen.com>
 * @license  http://opensource.org/licenses/OSL-3.0 OSL-3.0
 * @link     http://github.com/davidverholen
 */

namespace Bragento\Magento\Composer\Installer\Deploy\Mapping;

use Composer\Package\Package;
use Exception;
use Underscore\Types\Arrays;

/**
 * Class MappingNotFoundException
 *
 * @category Bragento_MagentoComposerInstaller
 * @package  Bragento\Magento\Composer\Installer\Deploy\Mapping
 * @author   David Verholen <david@verholen.com>
 * @license  http://opensource.org/licenses/OSL-3.0 OSL-3.0
 * @link     http://github.com/davidverholen
 */
class MappingNotFoundException extends \Exception
{
    public function __construct(
        Package $package,
        $code = 0,
        Exception $previous = null
    ) {
        $message = Arrays::implode([
            'Mapping for package not found: ',
            $package->getName()
        ]);
        parent::__construct(
            $message,
            $code,
            $previous
        ); // TODO: Change the autogenerated stub
    }
}
